name: Production Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version you're using

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec  # or your test command

      - name: Build assets
        run: bundle exec rake assets:precompile

      - name: Deploy to Production
        env:
          PRODUCTION_SERVER: ${{ secrets.PRODUCTION_SERVER }}
          PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}
          PRODUCTION_KEY: ${{ secrets.PRODUCTION_KEY }}
          PRODUCTION_DEPLOY_PATH: ${{ secrets.PRODUCTION_DEPLOY_PATH }}
        run: |
          scp -i $PRODUCTION_KEY -r ./build $PRODUCTION_USER@$PRODUCTION_SERVER:$PRODUCTION_DEPLOY_PATH
